### ISSUE TITLE
Parameter ddlx_options in ddlx_script:  is it ignored or not?

### ISSUE THREAD

**Issue by ayuryshev** [lacanoid/pgddl#17]
Please clarify is `ddlx_options text[] DEFAULT '{}'::text[]` used or not.

From what I see from code:

A. `ddlx_script` calls  `ddlx_script_parts($1,$2)` -  https://github.com/lacanoid/pgddl/blob/master/ddlx.sql#L2920
B. `ddlx_script_parts` calls `ddlx_create(oid,text[])` twice - https://github.com/lacanoid/pgddl/blob/master/ddlx.sql#L2894 
C. `ddlx_create(oid,text[])` ignores parameter `options`  - https://github.com/lacanoid/pgddl/blob/master/ddlx.sql#L2773

Am I missing something or not?

**Comment by lacanoid** [comment]
Currently not, but it is planned be used in the future to specify additional options.

**Comment by ayuryshev** [comment]
I read in Roadmap that you suppose to use type for options in future.

I propose to do it in a json form.

I was (and still)  in a need for a quick hack and did it this way (I don't like it but it's working):

```sql
CREATE TABLE ddlx_opts (
    opts jsonb NOT NULL
);

CREATE OR REPLACE FUNCTION public.ddlx_opts()
 RETURNS jsonb
 LANGUAGE sql
AS $function$
SELECT opts FROM ddlx_opts;
$function$;
```

Then I put in ddlx_opts:

```json
{
  "grants": { "disabled": true },
  "alter_owner": { "disabled": true },
  "create_regclass": { "alter_class_disabled": true }
}
```
Here each root-level  key is option for corresponding function:
- "grants" - 'ddlx_grants'
- "alter_owner" - 'ddlx_alter_owner'
- "create_regclass": - 'ddlx_create(reglass)'

This way it's possible to fine-tune behaviour of every ddlx-function.

And it's used in code this way:

```
CREATE OR REPLACE FUNCTION public.ddlx_alter_owner(oid)
 RETURNS text
 LANGUAGE sql
 STRICT
AS $function$
 with obj as (select * from ddlx_identify($1))
 select
   CASE
     WHEN COALESCE((ddlx_opts()->'alter_owner'->'disabled')::bool, FALSE) THEN ''
     when obj.sql_kind = 'INDEX' then ''
     else 'ALTER '||sql_kind||' '||sql_identifier||
          ' OWNER TO '||quote_ident(owner)||E';\n'
   end
  from obj 
$function$
;
```

What do you think?

I myself dislike global settings table but I did not found something easier/faster to implement.

**Comment by lacanoid** [comment]
My initial ideas were along those lines, too. I chose text[] instead of json because it is shorter and I don't really want to get too wild with the options, I'd prefer to keep them to the minimum. Plus, it's easy to split text to text[] and check if a word is in text[], whereas with json, one has to add a bunch of braces, quotes and semicolons.

Perhaps a better thing to do would be to refactor the whole extension to make better use of set-returning functions, so one could use "where" to select parts that one wants. This would require some major refactoring of the code, but it might be worthwhile.

**Comment by ayuryshev** [comment]
It's sad that postgresql don't have higher order functions.
It would be ideal for options IMHO.

> I don't really want to get too wild with the options, I'd prefer to keep them to the minimum.
I'm thinking about moving all templates for `format` to configuration.

E.g. 
```sql 
CREATE OR REPLACE FUNCTION public.ddlx_script(oid, ddlx_options text[] DEFAULT '{}'::text[])
 RETURNS text
 LANGUAGE sql
 STRICT
AS $function$
select E'BEGIN;\n\n'||
       format(
         E'/*\n%s%s*/\n\n%s%s',
         ddl_drop_deps||E'\n',
         ddl_drop,
         ddl_create,
         E'\n-- DEPENDANTS\n\n'||ddl_create_deps
       )||
       E'\nEND;\n'
  from ddlx_script_parts($1,$2)
$function$;
```
If  template `E'/*\n%s%s*/\n\n%s%s'` could be configured and there was no other string concatenation - than it would allow a lot. 

> Perhaps a better thing to do would be to refactor the whole extension to make better use of set-returning functions,
I like this idea.
You mean like 'ddlx_script_parts` but go even further? 

> This would require some major refactoring of the code, but it might be worthwhile.

I'm ready to help.
`pgddl` made my PostgreSQL life much better. 
Recreating chain of dependent objects was a pain before `pgddl`.

**Comment by lacanoid** [comment]
Set returning functions would be similar to ddlx_create and ddlx_script are now, but instead of single lump of SQL they would return a set of rows containg sql and other data, such as object name and id, statement type (pre-data, constraint, ddl, dcl) etc... this would allow one to easily select only a subset of this, say only the grant statements or pre-data table definitions. Basically, you would get what you get now, but in a more granular and structured form.

The functions as they are now would remain as they are convenient, but would use the underlying set returning functions.

Currently, function ddlx_create() is overloaded for various reg* types, but probably this needs to go away.
All calls will then initially go through single ddlx_create(oid) function, which can also handle the options.
Now there is a bunch of code in oveloaded functions such as ddlx_create(regclass), which needs to be considered.

Perhaps a way to approach this would be to create new ddlx_creates() and ddlx_scripts() set-returning analogues to ddlx_create() and ddlx_scripts() functions and play with those. 
They should return stuff from ddlx_identify() and ddlx_get_dependants() plus:
* sql statement itself
* extra tags 'DDL','DCL'
* section (base, storage, constraints, indexes, triggers, comments?)
* statement is an alter statement (idempotent)
* perhaps a structured (array) node numbering in dependancy tree, for sorting and such

**Comment by lacanoid** [comment]
This has been somewhat implemented in the form of new `ddlx_definitions(oid)` function.
This returns several sections as columns.

`ddlx_create()` now uses `ddlx_definitions` to get it's data.

**Comment by lacanoid** [comment]
Also options are now no longer ignored, but they are not documented yet.
